import { SampleShapeId, ShapeParams } from '@app/@types';

type SampleShapes = {
  [shapeId in SampleShapeId]: ShapeParams;
};

export const sampleShapeIds: SampleShapeId[] = [
  'ss00',
  'ss01',
  'ss02',
  'ss03',
  'ss04',
  'ss05',
  'ss06',
  'ss07',
  'ss08',
  'ss09',
  'ss10',
  'ss11',
  'ss12',
  'ss13',
  'ss14',
  'ss15',
  'ss16',
  'ss17',
  'ss18',
  'ss19',
  'ss20',
  'ss21',
  'ss22',
  'ss23',
  'ss24',
];

export const sampleShapes: SampleShapes = {
  ss00: {
    cornNum: 20,
    cornAmp: 0,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss01: {
    cornNum: 8,
    cornAmp: 0.1,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss02: {
    cornNum: 8,
    cornAmp: 0.3,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss03: {
    cornNum: 8,
    cornAmp: 0.5,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss04: {
    cornNum: 20,
    cornAmp: 0.1,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0.1,
    outerCurve: 0.2,
  },
  ss05: {
    cornNum: 20,
    cornAmp: 0.3,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss06: {
    cornNum: 20,
    cornAmp: 0.5,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss07: {
    cornNum: 8,
    cornAmp: 0.1,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss08: {
    cornNum: 8,
    cornAmp: 0.3,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss09: {
    cornNum: 8,
    cornAmp: 0.5,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss10: {
    cornNum: 20,
    cornAmp: 0.1,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0.1,
    outerCurve: 0.2,
  },
  ss11: {
    cornNum: 20,
    cornAmp: 0.3,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss12: {
    cornNum: 20,
    cornAmp: 0.5,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0.1,
    outerCurve: 0.4,
  },
  ss13: {
    cornNum: 8,
    cornAmp: 0.1,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss14: {
    cornNum: 8,
    cornAmp: 0.3,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss15: {
    cornNum: 8,
    cornAmp: 0.5,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss16: {
    cornNum: 20,
    cornAmp: 0.1,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss17: {
    cornNum: 20,
    cornAmp: 0.3,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss18: {
    cornNum: 20,
    cornAmp: 0.5,
    randomness: 0,
    randomSeed: 1,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss19: {
    cornNum: 8,
    cornAmp: 0.1,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss20: {
    cornNum: 8,
    cornAmp: 0.3,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss21: {
    cornNum: 8,
    cornAmp: 0.5,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss22: {
    cornNum: 20,
    cornAmp: 0.1,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss23: {
    cornNum: 20,
    cornAmp: 0.3,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0,
    outerCurve: 0,
  },
  ss24: {
    cornNum: 20,
    cornAmp: 0.5,
    randomness: 1,
    randomSeed: 3,
    innerCurve: 0,
    outerCurve: 0,
  },
};
