name: Status Check

on: [push]

jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint

  Type-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
          cache: 'yarn'
      - run: yarn install
      - run: yarn type-check

  Build-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
